// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_sign_in from "./routes/api/sign-in.ts";
import * as $api_sign_out from "./routes/api/sign-out.ts";
import * as $index from "./routes/index.tsx";
import * as $sign_in from "./routes/sign-in.tsx";
import * as $AuthForm from "./islands/AuthForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/sign-in.ts": $api_sign_in,
    "./routes/api/sign-out.ts": $api_sign_out,
    "./routes/index.tsx": $index,
    "./routes/sign-in.tsx": $sign_in,
  },
  islands: {
    "./islands/AuthForm.tsx": $AuthForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
